version: "3"
services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true
